import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SolanaProvider } from "./providers/solana-provider"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-neutral-950 text-neutral-100 antialiased">
        <SolanaProvider>
          {/* 👇 ocupa 100% del viewport, sin scroll global */}
          <div className="fixed inset-0 overflow-hidden">
            {/* fondo decorativo */}
            <div aria-hidden className="pointer-events-none absolute inset-0 -z-10">
              <div className="absolute inset-0 bg-[radial-gradient(1000px_600px_at_50%_-20%,rgba(88,28,135,.25),transparent)]" />
              <div className="absolute inset-0 [mask-image:linear-gradient(to_bottom,black,transparent_85%)] bg-[linear-gradient(to_right,rgba(255,255,255,.06)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,.06)_1px,transparent_1px)] bg-[size:18px_18px]" />
            </div>

            {/* área de contenido; si se pasa, scrollea SOLO aquí (puedes poner overflow-hidden si quieres 0 scroll) */}
            <main className="h-full w-full overflow-auto grid place-items-center p-6">
              {children}
            </main>
          </div>
        </SolanaProvider>
      </body>
    </html>
  );
}
